name: First Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: step one
       run: echo "step one"
     - name: step two
       run: echo "step two"
       
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@v1
      with:
        text: 'I am a cow! also, MOOOO!'
        color: 'blue'
          
